repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: python -m poetry run trailing-whitespace-fixer
        language: system
        types: [text]
        exclude: ^\.venv/

      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: python -m poetry run end-of-file-fixer
        language: system
        types: [text]
        exclude: ^\.venv/

      - id: check-yaml
        name: check-yaml
        entry: python -m poetry run check-yaml
        language: system
        types: [yaml]
        exclude: ^\.venv/

      - id: check-added-large-files
        name: check-added-large-files
        entry: python -m poetry run check-added-large-files
        language: system
        types: [file]
        stages: [pre-commit]
        exclude: ^\.venv/

      - id: debug-statements
        name: debug-statements
        entry: python -m poetry run debug-statement-hook
        language: system
        types: [python]
        exclude: ^\.venv/

      - id: detect-private-key
        name: detect-private-key
        entry: python -m poetry run detect-private-key
        language: system
        types: [text]
        exclude: ^\.venv/

      - id: mixed-line-ending
        name: mixed-line-ending
        entry: python -m poetry run mixed-line-ending
        language: system
        args: [--fix=lf]
        types: [text]
        exclude: ^\.venv/

      - id: ruff-check
        name: ruff (lint)
        entry: python -m poetry run ruff
        language: system
        args: [check, --fix, --exit-non-zero-on-fix]
        types: [python]
        exclude: ^\.venv/

      - id: ruff-format
        name: ruff (format)
        entry: python -m poetry run ruff
        language: system
        args: [format, --check]
        types: [python]
        exclude: ^\.venv/

      - id: mypy
        name: mypy
        entry: python -m poetry run mypy
        language: system
        args:
          [
            --ignore-missing-imports,
            --check-untyped-defs,
            --explicit-package-bases,
            -p,
            src,
            -p,
            scripts,
            -p,
            tests
          ]
        pass_filenames: false
        always_run: true
