services:
  redis:
    image: redis:7-alpine
    container_name: zdrav_redis
    command: redis-server --save 60 1 --loglevel warning --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always
